version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/bot"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/server"
    schedule:
      interval: "daily"

