
services:
  server:
    build:
      context: ./server
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - client-build:/app/wwwroot
      - ./logs:/app/logs
    depends_on:
      - client
    ports:
      - "8080:8080"
  
  client:
    build:
      context: ./client
      target: build
    environment:
      - NODE_ENV=production
    volumes:
      - client-build:/app/build

  bot:
    build:
      context: ./bot
    environment:
      - ENV=production
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    volumes:
      - type: volume
        source: ./logs/bot.log
        target: /app/bot.log
    depends_on:
      - server

  #db:
  #  image: postgres:17
  #  volumes:
  #    - db-data:/var/lib/postgresql/data
  #  environment:
    
volumes:
  client-build:
