// <auto-generated />
using KoodaamoJukebox.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KoodaamoJukebox.Database.Migrations
{
    [DbContext(typeof(KoodaamoJukeboxDbContext))]
    [Migration("20250717184143_UserBanning")]
    partial class UserBanning
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KoodaamoJukebox.Database.Models.HlsPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("WebpageUrlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WebpageUrlHash")
                        .IsUnique();

                    b.ToTable("HlsPlaylists", (string)null);
                });

            modelBuilder.Entity("KoodaamoJukebox.Database.Models.HlsSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("WebpageUrlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DownloadUrlHash")
                        .IsUnique();

                    b.HasIndex("WebpageUrlHash");

                    b.ToTable("HlsSegments", (string)null);
                });

            modelBuilder.Entity("KoodaamoJukebox.Database.Models.QueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ShuffleIndex")
                        .HasColumnType("integer");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Index");

                    b.HasIndex("TrackId");

                    b.ToTable("QueueItems", (string)null);
                });

            modelBuilder.Entity("KoodaamoJukebox.Database.Models.RoomInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentTrackId")
                        .HasColumnType("text");

                    b.Property<int?>("CurrentTrackIndex")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLooping")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShuffled")
                        .HasColumnType("boolean");

                    b.Property<long?>("PausedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("PlayingSince")
                        .HasColumnType("bigint");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTrackId");

                    b.HasIndex("CurrentTrackIndex");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("Queues", (string)null);
                });

            modelBuilder.Entity("KoodaamoJukebox.Database.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ThumbnailHigh")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailLow")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Uploader")
                        .HasColumnType("text");

                    b.Property<string>("WebpageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebpageUrlHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WebpageUrl")
                        .IsUnique();

                    b.HasIndex("WebpageUrlHash")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("KoodaamoJukebox.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedRoomCode")
                        .HasColumnType("text");

                    b.Property<string>("BannedReason")
                        .HasColumnType("text");

                    b.Property<long?>("BannedUntil")
                        .HasColumnType("bigint");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("boolean");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedRoomCode");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
