name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-client:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Install dependencies
      working-directory: ./client
      run: pnpm install

    - name: Run linter
      working-directory: ./client
      run: pnpm lint

    - name: Run tests
      working-directory: ./client
      run: pnpm test -- --coverage --watchAll=false --coverageReporters="text" --coverageReporters="lcov"

    - name: Upload client coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./client/coverage/lcov.info
        flags: client
        name: client-coverage

  test-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      working-directory: ./server
      run: dotnet restore

    - name: Build
      working-directory: ./server
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      working-directory: ./server
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./test-results

    - name: Upload server coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./server/test-results/*/coverage.cobertura.xml
        flags: server
        name: server-coverage
